#!/usr/bin/env bash

printHeading() {
    printf "\n\033[0;36m%s\033[0m \n" "$1"
}


printHeading "Installing homebrew"

# Check for Homebrew,
# Install if we don't have it
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Homebrew already installed. Skipping."
fi

echo "Updating homebrew..."
brew update
echo "Installing packages..."
brew bundle

printHeading "Installing Command Line Tools"
if xcode-select -p &>/dev/null; then
  echo "Command Line Tools already installed. Skipping."
else
  xcode-select --install
fi

printHeading "Symlinking dotfiles"
sh symlink

printHeading "Setting OSX settings"
sh mac

echo "Done. Note that some of these changes require a logout/restart to take effect."
echo "Remember to add the Raycast config file manually! \n"
echo "Press Enter to restart Dock and Finder or Ctrl+C to cancel."
read -r

killall Dock
killall Finder



