#!/usr/bin/sh

printHeading() {
    printf "\n\e[0;36m$1\e[0m \n"
}


printHeading "Installing homebrew"

# Check for Homebrew,
# Install if we don't have it
if test ! $(which brew); then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else 
  echo "Homebrew already installed. Skipping."
fi

echo "Updating homebrew..."
brew update
echo "Installing packages..."
brew bundle

printHeading "Installing Command Line Tools"
if xcode-select -p 1>/dev/null; then
echo "Command Line Tools already installed. Skipping."
else
  xcode-select --install  
fi

printHeading "Installing Bun"
if ! command -v bun &> /dev/null; then
  curl -fsSL https://bun.sh/install | bash
else
  echo "Bun is already installed. Skipping."
fi

printHeading "Installing fasd"
if ! command -v fasd &> /dev/null; then
  curl -L -o fasd.tar.gz https://github.com/clvv/fasd/tarball/1.0.1
  tar -xzf fasd.tar.gz
  cd clvv-fasd-4822024/
  sudo make install
  rm -rf fasd.tar.gz clvv-fasd-4822024/
else
  echo "fasd is already installed. Skipping."
fi

printHeading "Setting OSX settings"
sh mac

echo "Done. Note that some of these changes require a logout/restart to take effect."
echo "Remember to add the Raycast config file manually! \n"
echo "Press Enter to restart Dock, Finder and iTerm2 or Ctrl+C to cancel."
read -r

killall Dock
killall Finder
killall iTerm2



